<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Product>Simple Java Property Editor</Product>
    <AssemblyTitle>Simple Java Property Editor</AssemblyTitle>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

</Project>